# Site settings
title: Cristian Mitroi's resume
description: >- # this means to ignore newlines until "baseurl:"
  Software Developer. Passionate about the intersection between technology, creativity, and culture.
baseurl: "/resume"  # the subpath of your site, e.g. /blog
url: "cristianmtr.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: cristianmtr/resume


# Build settings
markdown: kramdown
plugins:
  - jemoji


# Author Info
author:
  name     : Cristian Mitroi
  image    : assets/face.jpg
  email    : cristi dot mtr at gmail dot com
  github   : cristianmtr
  linkedin : cristianmitroi


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock