# Site settings
title: Dajana Ivkic - Resume
description: >- # this means to ignore newlines until "baseurl:"
  Deep Learning Research Assitant.
baseurl: "/resume"  # the subpath of your site, e.g. /blog
url: "idajana.github.io" # the base hostname & protocol for your site, e.g. http://example.com
repository: idajana/resume


# Build settings
markdown: kramdown
plugins:
  - jemoji


# Author Info
author:
  name     : Dajana Ivkic
  image    : assets/profilna.png
  email    : ivkic dot dajana at gmail dot com
  github   : idajana
  linkedin : dajana-ivkic-29549311a


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock